switch to ESM module resolution
Adding "type": "module" avoids errors like the following:

    source/options-storage.ts:1:25 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("webext-options-sync")' call instead.
      To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/home/adam/blockchain/git/rolod0x/package.json'.

    1 import OptionsSync from 'webext-options-sync';
                              ~~~~~~~~~~~~~~~~~~~~~

but then "moduleResolution": "node" is required to avoid errors like:

    source/replacer.ts:1:24 - error TS2835: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './types.js'?